fbhackaton/config/routes.rb
Rails.application.routes.draw do
  get 'maps', to: "maps#index"
  get 'maps/show', to: "maps#show"
  get 'topics/display', to: "topics#display"
  get 'twitter/weighting', to: "twitter#weighting"

  resources :topics
  resources :votes

  devise_for :users
  root 'home#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

fbhackaton/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

fbhackaton/app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
end

fbhackaton/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :topics
  has_many :votes
  
end

fbhackaton/app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :topic  
end

fbhackaton/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

fbhackaton/app/controllers/bubbles_controller.rb
class BubblesController < ApplicationController
  def index
    @usuario = User.first
    @nombre = @usuario['name']
    @descontento = Dislike.first
    @union = Disliked.first
    gon.your_variable = @nombre

  end

  def up_quantity
    puts 'hola'

    @descontento = Dislike.find(params[:dislike_id])
    puts @descontento.name
    @descontento.quantity += 1
    @descontento.save
  end


  def get_quantity
    @descontento = Dislike.find(params[:dislike_id]).quantity
    render :json => {"quantity" => @descontento.to_json.to_s}

  end

end

fbhackaton/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end


end

fbhackaton/app/controllers/main_controller.rb
class MainController < ApplicationController
  def show
  end


  def map
  end
end

fbhackaton/app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def show
    @topics = Topic.all
    @topics_json = Topic.all.to_json.to_s
  end

  def index
  end


end

fbhackaton/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    p user.password
         if user and (params[:password] == user.password)
          session[:user_id] = user.id
          redirect_to '/main'
        end
  end

  def destroy
  end
end

fbhackaton/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :get_topics, only: [:show, :display]
  before_action :set_topic, only: [:show, :update, :edit, :destroy]

  def index
    @topic = Topic.find(params[:id])
  end

  def display
    @topics = Topic.all.order('votes desc')
  end

  def show
    @topic = Topic.find(params[:id])
    render :json => @topic.to_json
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.save
  end

  def edit
    @users = User.all
  end

  def update
    @descontento = Topic.find(params[:id])
    @descontento.votes += 1000
    @descontento.save
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_topics
      @topics = Topic.all
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:name, :description, :votes, :user_id, :lat, :lon)
    end

end

fbhackaton/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :get_votes, only: [:show, :index]
  before_action :set_vote, only: [:show, :update, :edit, :destroy]

  def index
    @votes = Vote.all
  end

  def show
    @vote = Vote.find(params[:id])
  end

  def new
    @vote = Vote.new
  end

  def create
    @vote = Vote.new(vote_params)
    @vote.save
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_votes
      @votes = Vote.all
    end

    def set_vote
      @vote = Vote.find(params[:id])
    end

    def vote_params
      params.require(:vote).permit(:name, :description, :votes, :user_id, :lat, :lon)
    end


end

fbhackaton/app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Dislike"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def active_class(c, i)
    current_page?(controller: c, action: i) ? "active" : ""
  end

end

fbhackaton/app/helpers/bubbles_helper.rb
module BubblesHelper
end

fbhackaton/app/helpers/home_helper.rb
module HomeHelper
end

fbhackaton/app/helpers/main_helper.rb
module MainHelper
end

fbhackaton/app/helpers/maps_helper.rb
module MapsHelper
end

fbhackaton/app/helpers/sessions_helper.rb
module SessionsHelper
end

fbhackaton/app/helpers/topics_helper.rb
module TopicsHelper
end

fbhackaton/app/helpers/twitter_helper.rb
module TwitterHelper
end

fbhackaton/app/helpers/votes_helper.rb
module VotesHelper
end

fbhackaton/app/views/bubbles/index.html.erb
<!DOCTYPE html>
<html>
    <head>
		<title>Bubble Click</title>


        <%= include_gon %>

        <script>

          $(document).ready(function() {

              $('div').dblclick(function() {

                  $(this).toggleClass('div active');

                  $.ajax({
                              url: "/bubbles/up_quantity",
                              method: "POST",
                              data: { dislike_id: <%=@descontento.id%>},
                          });

                  $.ajax({
                              url: "/dislikes",
                              type: "GET",
                              data: { dislike_id: <%=@descontento.id%>},
                              dataType: "json",
                              success: function(data) {
                                var new_quantity = data.quantity;
                                document.getElementById('quantity').innerHTML = "Quantity:" + new_quantity;

                                  }
                                });



              });
          });



        </script>

        <style>
        div {
            height: 100px;
            width: 100px;
            border-radius: 5px;
            background-color: blue;
        }
        .active{
            background-color: lightblue;
            height: 200px;
            width: 200px;
        }

        </style>





	</head>
	<body>
        <div></div>
        <p> User name: <%= @nombre %> </p>
        <p> Dislike: <%= @descontento.name %> </p>
        <p id="quantity"> Quantity: <%= @descontento.quantity %> </p>


</div>


<a href="#" onclick="paintIt(this, '#990000')">Paint it red</a>
	</body>
</html>

fbhackaton/app/views/home/index.html.erb
<% provide(:title, 'Home') %>
<head>
  <style>
  body{
      background: url('back.jpg') no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
      }
  button {
        background-color: #FFFFFF; /* Green */
        border: none;
        color: black;
        font-weight: bold;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 4px;
    }
  .divclass
  {
    position: fixed;
    bottom: 28%;
    left: 51%;
}


  </style>


</head>


<body>
<div class="divclass">
  <form action="/maps/show" method="get">
  <button>See what people Dislike</button>
</form>
</div>
</body>

fbhackaton/app/views/home/show.html.erb
<h1> Home </h1>

<a href="/login"><h2>Login</h2> </a>

fbhackaton/app/views/main/map.html.erb
<h1>Mapa de Dislikes</h1>
<div id="map-container">
  <div id="map-canvas"></div>
</div>

fbhackaton/app/views/main/show.html.erb
<h1>Main</h1>

<a href='/dislikes/'><h2> Dislikes </h2></a>

<a href='/dislikeds/'><h2> Dislike a Dislike </h2></a>

<h2> <%= link_to "Mapa", main_map_path %> </h1>

fbhackaton/app/views/maps/index.html.erb
<h1>map</h1>
<p>Find me in app/views/maps/map.html.erb</p>

fbhackaton/app/views/maps/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Map</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 93%;
        weight: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        weight: 100%;
        margin: 0;
        padding: 0;
        margin-top: 0;

      }
    </style>
  </head>
  <body>

  <div id="map"></div>

    <script>
      var map;

      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: new google.maps.LatLng(13.455670, -10.668291),
          zoom: 3
        });
        var markers = []
        var circles = []
        var colors = ['#dd0000', '#c10000', '#b00000', '#a10101','#980000', '#ffc04c', '#faad58', '#f59a64', '#f0866f', '#eb737b'];

        for (var i = 1; i < <%= @topics.length + 1%>; i++) {
          (function(i) {
          $.ajax({
                url: "/topics",
                type: "GET",
                data: { id: i },
                dataType: "json",
                success: function(data) {
                  var topico = data;
                  var new_quantity = data.votes;
                  circles[i] =  new google.maps.Circle({
                        strokeColor: '#FF0000',
                        strokeOpacity: 0.8,
                        strokeWeight: 2,
                        fillColor: colors[i],
                        fillOpacity: 0.9,
                        map: map,
                        center: new google.maps.LatLng(parseFloat(topico.lat), parseFloat(topico.lon)),
                        radius: new_quantity*(data.weight*20)**2
                      });
                      console.log(parseFloat(topico.lat))
                      markers[i] = new google.maps.Marker({
                        position: new google.maps.LatLng(parseFloat(topico.lat), parseFloat(topico.lon)),
                        map: map,
                        icon : { url: "http://icons.iconarchive.com/icons/graphicloads/flat-finance/256/dislike-icon.png",
                                scaledSize: new google.maps.Size(50, 50),
                              labelOrigin: new google.maps.Point(25, 60)},
                                label: {
            color: 'black',
            fontWeight: 'bold',
            text: data.name
          },
                      });
                  console.log(i);
                  (function(marker, this1){
                    google.maps.event.addListener(marker, 'click', function(){
                              $.ajax({
                                         url: "/topics/".concat(this1),
                                         method: "PATCH",
                                         success: function(data) {
                                           $.ajax({
                                               url: "/topics",
                                               type: "GET",
                                               data: {id: this1},
                                               dataType: "json",
                                               success: function(data) {
                                                  console.log(data);
                                                   var new_quantity2 = data.votes;
                                                   console.log(new_quantity2)
                                                   circles[this1].setRadius(new_quantity2*(data.weight*20)**2)
                                                     }
                                                   });
                                                 }
                                     });
                              });
                            }(markers[i],i));
                    }
                  });
                })(i);
              }
      };
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBe2hbwn4AgnLCls4l-GpOBBdN5AcmaiTE
&callback=initMap"
    async defer></script>
</body>
</html>

fbhackaton/app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

fbhackaton/app/views/topics/destroy.html.erb
<h1>Topics#destroy</h1>
<p>Find me in app/views/topics/destroy.html.erb</p>

fbhackaton/app/views/topics/display.html.erb
<!--<% provide(:title, 'Topics') %>

	<%@topics.each do |topic|%>
		<% descript = topic.name + ": " + topic.description %>
		<h2><%= link_to descript , topic_path(topic)%></h2>
	<% end %>

	<%= link_to "Add Topic", new_topic_path %>-->
	<!--<% provide(:title, 'New Topic') %>
	<div class="row">
	    <div class="col-sm-6" style="text-align: left; margin-left:15px">
	      <table class="table forum table-striped">
	        <thead>
	          <tr>
	            <th class="cell-stat-2x hidden-xs hidden-sm">Topic</th>
	            <th class="cell-stat-2x hidden-xs hidden-sm">Description</th>
							<th class="cell-stat-2x hidden-xs hidden-sm">Votes</th>
							<th class="cell-stat-2x hidden-xs hidden-sm">Twitter weight</th>
	          </tr>
	        </thead>

	        <tbody>
	          <% @topics.each do |topic| %>
	            <tr>
	              <td class="cell-stat-2x hidden-xs hidden-sm"><%= topic.name %></td>
	              <td class="cell-stat-2x hidden-xs hidden-sm"><%= topic.description %></td>
								<td class="cell-stat-2x hidden-xs hidden-sm"><%= topic.votes %></td>
								<td class="cell-stat-2x hidden-xs hidden-sm"><%= topic.weight%></td>
							</tr>
	          <% end %>
	        </tbody>
	      </table>
	    </div>
	    <div class="col-sm-1"></div>
	    <div class="col-sm-4">
	      <h1>New Topic</h1>
	    </div>
	    <div class="col-sm-1"></div>
	</div>-->
<head>
	<style>
	th{
    background-color: #292c41 ;
    color: #FFFFFF ;
  }
  td{
    background-color: #FFFFFF ;
    color: #000000 ;
  }
	</style>
</head>
<body>
	<table class="table forum table-inverse">
	                <thead class="thead-inverse">
	                  <tr>
	                    <th class="cell-stat-2x hidden-xs hidden-sm">Ranking</th>
	                    <th class="cell-stat-2x hidden-xs hidden-sm">Topic</th>
	                    <th class="cell-stat-2x hidden-xs hidden-sm">Description</th>
	                    <th class="cell-stat-2x hidden-xs hidden-sm">Dislikes</th>
	                    <th class="cell-stat-2x hidden-xs hidden-sm">Twitter Weight</th>
	                  </tr>
	                </thead>

	                <tbody>
	                  <% count = 1%>
	                  <% @topics.each do |topic| %>
	                    <tr>
	                      <td class="cell-stat-2x hidden-xs hidden-sm" >
	                        <%= "#" + count.to_s %>
	                        <% count += 1%>
	                      </td>
	                      <td class="cell-stat-2x hidden-xs hidden-sm" >
	                        <%= topic.name%>
	                      </td>
	                      <td class="cell-stat-2x hidden-xs hidden-sm">
	                        <%= topic.description %></td>
	                      <td class="cell-stat-2x hidden-xs hidden-sm">
	                          <%= topic.votes %></td>
	                          <td class="cell-stat-2x hidden-xs hidden-sm">
	                              <%= topic.weight %></td>
	                    </tr>
	                  <% end %>
	                </tbody>
	              </table>
</body>

fbhackaton/app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

fbhackaton/app/views/topics/index.html.erb
<% provide(:title, 'Topics') %>

	<%@topics.each do |topic|%>
		<% descript = topic.name + ": " + topic.description %>
		<h2><%= link_to descript , topic_path(topic)%></h2>
	<% end %>

	<%= link_to "Add Topic", new_topic_path %>

fbhackaton/app/views/topics/new.html.erb
<% provide(:title, 'New Topic') %>
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
      <h1>New Topic</h1>
    	<%= render 'form' %>
    </div>
    <div class="col-sm-4"></div>
</div>

fbhackaton/app/views/topics/show.html.erb
<h1>Topics#show</h1>
<p>Find me in app/views/topics/show.html.erb</p>

fbhackaton/app/views/topics/update.html.erb
<h1>Topics#update</h1>
<p>Find me in app/views/topics/update.html.erb</p>

fbhackaton/app/views/votes/_form.html.erb
<%= simple_form_for(@vote) do |f| %>
  <%= f.error_notification %>
  <%= f.input :user_id, collection: @users, label_method: :name, label_value: :id, include_blank: false, label: "Creator"%>
  <%= f.input :topic_id, collection: @topics, label_method: :name, label_value: :id, include_blank: false, label: "Topic"%>
  <%= f.button :submit, "Create Vote", :class => 'btn btn-success' %>
<% end %>

fbhackaton/app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

fbhackaton/app/views/votes/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>

fbhackaton/app/views/votes/index.html.erb
<% provide(:title, 'Votes') %>
<head>
	<style>
	th{
    background-color: #292c41 ;
    color: #FFFFFF ;
  }
  td{
    background-color: #FFFFFF ;
    color: #000000 ;
  }
	</style>
</head>
<body>
	<div class="row">
	    <div class="col-sm-6" style="text-align: left; margin-left:15px">
	      <table class="table forum table-striped">
					<tbody>
						<th class="cell-stat-2x hidden-xs hidden-sm">Votes</th>
	          <% @votes.each do |vote| %>
	            <tr>
								<td class="cell-stat-2x hidden-xs hidden-sm"><%=User.find(vote.user_id).name + " voted for " + Topic.find(vote.topic_id).name %></td>
							</tr>
	          <% end %>
	        </tbody>
	      </table>
	    </div>
	    <div class="col-sm-1"></div>
	    <div class="col-sm-4">
	    </div>
	    <div class="col-sm-1"></div>
	</div>
</body>

fbhackaton/app/views/votes/new.html.erb
<% provide(:title, 'New Vote') %>
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
      <h1>New Vote</h1>
    	<%= render 'form' %>
    </div>
    <div class="col-sm-4"></div>
</div>

fbhackaton/app/views/votes/show.html.erb
<h1>Votes#show</h1>
<p>Find me in app/views/votes/show.html.erb</p>